# Generated by Django 4.2.2 on 2023-06-26 08:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dish', models.CharField(max_length=100)),
                ('full_details', jsonfield.fields.JSONField()),
            ],
        ),
    ]
