# Generated by Django 4.2.2 on 2023-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_details',
            name='full_details',
        ),
        migrations.RemoveField(
            model_name='restaurant_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='restaurant_details',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
